name: CocoaExposed
description: iOS and OSX tips, tricks and tutorials by Valentin Radu, software engineer interested in the area of signal processing, computer graphics and machine learning.
meta_description: "iOS and OSX related tips, tricks and tutorials"

aboutPage: true

gems:
 - jekyll-paginate

markdown: kramdown
kramdown:
  smart_quotes: apos,apos,quot,quot
  parse_block_html: false
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://cocoaexposed.com'
google_analytics: 'UA-37620980-1'
disqus: true
disqus_shortname: 'cocoaexposed'

# Details for the RSS feed generator
url:            'http://cocoaexposed.com'
author:         'Valentin Radu'
authorTwitter:  'CocoaExposed'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
